on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches: ["ulm"]

concurrency:
  group: run-tests

jobs:
  blockchain-tests:
    runs-on: [self-hosted, aws, us-east-2, m6a.4xlarge]

    permissions:
      contents: read
      packages: read

    steps:
      - uses: docker/login-action@v3
        name: Login to GitHub Container Registry
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Check out repository
        uses: actions/checkout@v4

      - name: 'Set up Docker'
        uses: ./.github/actions/with-docker
        with:
          container-name: kevm-ci-concrete-${{ github.sha }}
          github-app-id: ${{ vars.CICD_GITHUB_WEBAPP_ID }}
          github-app-private-key: ${{ secrets.CICD_GITHUB_WEBAPP_PRIVATE_KEY }}

      - name: 'Debug environment'
        run: |
          docker exec -u test-user kevm-ci-concrete-${{ github.sha }} \
            /bin/bash -c 'ls -la /app/vlm/kllvm && whoami && id && pwd'

      - name: 'Run the ULM BLockchain Tests: TestULMBlockchain'
        run: |
          docker exec \
            -u test-user \
            --workdir /app/evm-semantics \
            kevm-ci-concrete-${{ github.sha }} \
            /bin/bash -c 'make test-vlm-blockchain'

      - name: 'Run the Blockchain Spec: TestsTestSpecBlockchain'
        run: |
          docker exec \
            -u test-user \
            --workdir /app/evm-semantics\
            kevm-ci-concrete-${{ github.sha }} \
            /bin/bash -c 'make test-spec-blockchain'

      - name: 'Run the Ethereum Conformance Tests: TestBlockchain'
        run: |
          docker exec \
            -u test-user \
            --workdir /app/evm-semantics\
            kevm-ci-concrete-${{ github.sha }} \
            /bin/bash -c 'make test-blockchain'
