on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches: ["ulm"]

concurrency:
  group: run-tests

jobs:
  blockchain-tests:
    runs-on: [self-hosted, aws, us-east-2, m6a.4xlarge]

    permissions:
      contents: read
      packages: read

    steps:
      - uses: actions/create-github-app-token@v1
        id: temp-token
        name: Generate temporary GitHub Token
        with:
          app-id: ${{ vars.CICD_GITHUB_WEBAPP_ID }}
          private-key: ${{ secrets.CICD_GITHUB_WEBAPP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - uses: docker/login-action@v3
        name: Login to GitHub Container Registry
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Check out repository
        uses: actions/checkout@v4

      - name: 'Set up Docker'
        uses: ./.github/actions/with-docker
        with:
          container-name: kevm-ci-concrete-${{ github.sha }}
          github-app-id: ${{ vars.CICD_GITHUB_WEBAPP_ID }}
          github-app-private-key: ${{ secrets.CICD_GITHUB_WEBAPP_PRIVATE_KEY }}

      - name: 'Run the ULM BLockchain Tests: TestULMBlockchain'
        uses: nick-invision/retry@v3
        with:
          timeout_minutes: 10
          max_attempts: 3
          retry_on: error
          command: |
            docker exec \
              -u test-user \
              --workdir /app/evm-semantics \
              kevm-ci-concrete-${{ github.sha }} \
              /bin/bash -c 'make test-vlm-blockchain'

      - name: 'Run the Blockchain Spec Tests: TestSpecBlockchain'
        uses: nick-invision/retry@v3
        with:
          timeout_minutes: 10
          max_attempts: 3
          retry_on: error
          command: |
            docker exec \
              -u test-user \
              --workdir /app/evm-semantics\
              kevm-ci-concrete-${{ github.sha }} \
              /bin/bash -c 'make test-spec-blockchain'

      - name: 'Run the Ethereum Conformance Tests: TestBlockchain'
        uses: nick-invision/retry@v3
        with:
          timeout_minutes: 10
          max_attempts: 3
          retry_on: error
          command: |
            docker exec \
              -u test-user \
              --workdir /app/evm-semantics\
              kevm-ci-concrete-${{ github.sha }} \
              /bin/bash -c 'make test-blockchain'
