name: 'Test PR'
on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master-update'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  kevm-pyk-code-quality-checks:
    name: 'Code Quality Checks'
    runs-on: ubuntu-latest
    steps:
      - name: 'Setup Python 3.10'
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: 'Check out code'
        uses: actions/checkout@v4
      - name: 'Install Poetry'
        uses: Gr1N/setup-poetry@v9
      - name: 'Run code quality checks'
        run: make -C kevm-pyk check
      - name: 'Run pyupgrade'
        run: make -C kevm-pyk pyupgrade

  kevm-pyk-unit-tests:
    needs: kevm-pyk-code-quality-checks
    name: 'Unit Tests'
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out code'
        uses: actions/checkout@v4
      - name: 'Install Poetry'
        uses: Gr1N/setup-poetry@v9
      - name: 'Run unit tests'
        run: make -C kevm-pyk cov-unit

  kevm-pyk-profile:
    needs: kevm-pyk-code-quality-checks
    name: 'Profiling'
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out code'
        uses: actions/checkout@v4
      - name: 'Install Poetry'
        uses: Gr1N/setup-poetry@v9
      - name: 'Run profiling'
        run: |
          make -C kevm-pyk profile

  test-concrete-execution:
    name: 'Conformance Tests'
    needs: kevm-pyk-code-quality-checks
    runs-on: [self-hosted, aws, us-east-2, m6a.4xlarge]
    timeout-minutes: 90
    steps:
      - name: 'Check out code'
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: 'Set up Docker'
        uses: ./.github/actions/with-docker
        with:
          container-name: kevm-ci-concrete-${{ github.sha }}
      - name: 'Build kevm-pyk'
        run: docker exec -u github-user kevm-ci-concrete-${{ github.sha }} /bin/bash -c 'make poetry'
      - name: 'Build targets'
        run: docker exec -u github-user kevm-ci-concrete-${{ github.sha }} /bin/bash -c 'CXX=clang++-14 poetry -C kevm-pyk run kdist --verbose build -j`nproc` evm-semantics.kllvm evm-semantics.kllvm-runtime'
      - name: 'Test integration'
        run: docker exec -u github-user kevm-ci-concrete-${{ github.sha }} /bin/bash -c 'make test-integration'
      - name: 'Test conformance'
        run: docker exec -u github-user kevm-ci-concrete-${{ github.sha }} /bin/bash -c 'make test-conformance'
      - name: 'Test llvm krun'
        run: docker exec -u github-user kevm-ci-concrete-${{ github.sha }} /bin/bash -c 'make test-interactive'
      - name: 'Tear down Docker'
        if: always()
        run: |
          docker stop --time=0 kevm-ci-concrete-${{ github.sha }}
