name: 'Update Version'
on:
  push:
    branches:
      - '_update-deps/runtimeverification/blockchain-k-plugin'
      - '_update-deps/runtimeverification/pyk'
  workflow_dispatch:
# Stop in progress workflows on the same branch and same workflow to use latest committed code
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  update-versions:
    name: 'Update Dependency Versions'
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out code'
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.JENKINS_GITHUB_PAT }}
          fetch-depth: 0
      - name: 'Configure GitHub user'
        run: |
          git config user.name devops
          git config user.email devops@runtimeverification.com
      - name: 'Install Poetry'
        uses: Gr1N/setup-poetry@v8
      - name: 'Update pyk release tag'
        run: |
          PYK_VERSION="$(cat deps/pyk_release)"
          sed -i 's!pyk = { git = "https://github.com/runtimeverification/pyk.git", tag="[v0-9\.]*" }!pyk = { git = "https://github.com/runtimeverification/pyk.git", tag="'${PYK_VERSION}'" }!' kevm-pyk/pyproject.toml
          poetry -C kevm-pyk update
          git add kevm-pyk/ && git commit -m "kevm-pyk/: sync poetry files pyk version ${PYK_VERSION}" || true
      - name: 'Update K release file'
        run: |
          K_VERSION=$(poetry -C kevm-pyk run python3 -c 'import pyk; print(pyk.K_VERSION)')
          echo ${K_VERSION} > deps/k_release
          git add deps/k_release && git commit -m "deps/k_release: sync release file version ${K_VERSION}" || true
      - name: 'Update plugin release file'
        run: |
          BKP_VERSION=$(git -C kevm-pyk/src/kevm_pyk/kproj/plugin rev-parse HEAD)
          echo ${BKP_VERSION} > deps/blockchain-k-plugin_release
          git add deps/blockchain-k-plugin_release && git commit -m "deps/blockchain-k-plugin_release: sync release file version ${BKP_VERSION}" || true
      - name: 'Push updates'
        run: git push
